//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccount) DeepCopyInto(out *StorageAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccount.
func (in *StorageAccount) DeepCopy() *StorageAccount {
	if in == nil {
		return nil
	}
	out := new(StorageAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountKey) DeepCopyInto(out *StorageAccountKey) {
	*out = *in
	in.CreationTime.DeepCopyInto(&out.CreationTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountKey.
func (in *StorageAccountKey) DeepCopy() *StorageAccountKey {
	if in == nil {
		return nil
	}
	out := new(StorageAccountKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountKeyRegenerator) DeepCopyInto(out *StorageAccountKeyRegenerator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountKeyRegenerator.
func (in *StorageAccountKeyRegenerator) DeepCopy() *StorageAccountKeyRegenerator {
	if in == nil {
		return nil
	}
	out := new(StorageAccountKeyRegenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageAccountKeyRegenerator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountKeyRegeneratorList) DeepCopyInto(out *StorageAccountKeyRegeneratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageAccountKeyRegenerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountKeyRegeneratorList.
func (in *StorageAccountKeyRegeneratorList) DeepCopy() *StorageAccountKeyRegeneratorList {
	if in == nil {
		return nil
	}
	out := new(StorageAccountKeyRegeneratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageAccountKeyRegeneratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountKeyRegeneratorSpec) DeepCopyInto(out *StorageAccountKeyRegeneratorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountKeyRegeneratorSpec.
func (in *StorageAccountKeyRegeneratorSpec) DeepCopy() *StorageAccountKeyRegeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(StorageAccountKeyRegeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountKeyRegeneratorStatus) DeepCopyInto(out *StorageAccountKeyRegeneratorStatus) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]StorageAccountKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountKeyRegeneratorStatus.
func (in *StorageAccountKeyRegeneratorStatus) DeepCopy() *StorageAccountKeyRegeneratorStatus {
	if in == nil {
		return nil
	}
	out := new(StorageAccountKeyRegeneratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountList) DeepCopyInto(out *StorageAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountList.
func (in *StorageAccountList) DeepCopy() *StorageAccountList {
	if in == nil {
		return nil
	}
	out := new(StorageAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountProperties) DeepCopyInto(out *StorageAccountProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountProperties.
func (in *StorageAccountProperties) DeepCopy() *StorageAccountProperties {
	if in == nil {
		return nil
	}
	out := new(StorageAccountProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountSpec) DeepCopyInto(out *StorageAccountSpec) {
	*out = *in
	out.Properties = in.Properties
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountSpec.
func (in *StorageAccountSpec) DeepCopy() *StorageAccountSpec {
	if in == nil {
		return nil
	}
	out := new(StorageAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountStatus) DeepCopyInto(out *StorageAccountStatus) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]StorageAccountKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountStatus.
func (in *StorageAccountStatus) DeepCopy() *StorageAccountStatus {
	if in == nil {
		return nil
	}
	out := new(StorageAccountStatus)
	in.DeepCopyInto(out)
	return out
}
