apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "storage-account.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "storage-account.name" . }}-system

  
  