apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage-account.name" . }}-controller-manager-metrics-service
  namespace: {{ include "storage-account.name" . }}-system
  labels:
    {{- include "storage-account.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    control-plane: controller-manager
