---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccountkeyregenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccountkeyregenerators/finalizers
  verbs:
  - update
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccountkeyregenerators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
  - update
