# permissions for end users to edit storageaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storageaccount-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: storage-account
    app.kubernetes.io/part-of: storage-account
    app.kubernetes.io/managed-by: kustomize
  name: storageaccount-editor-role
rules:
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - blob.arcblob.poc
  resources:
  - storageaccounts/status
  verbs:
  - get
